---
# ==============================================================================
#   Installation
# ==============================================================================

- name: Podman | Debian
  block:

    - name: Debian | Add ppa
      become: true
      apt_repository:
        repo: "{{ podman_ppa }}"
        codename: "{{ ansible_distribution_release }}"
        state: present

  when: ansible_os_family == 'Debian'

- name: Podman | RedHat
  block:

    - name: RedHat | add prerequisites
      become: true
      yum_repository:
        name: vbatts-shadow-utils-newxidmap
        description: Copr repo for shadow-utils-newxidmap owned by vbatts
        file: vbatts-shadow-utils-newxidmap-epel-7
        baseurl: https://copr-be.cloud.fedoraproject.org/results/vbatts/shadow-utils-newxidmap/epel-7-$basearch/
        gpgcheck: yes
        gpgkey: https://copr-be.cloud.fedoraproject.org/results/vbatts/shadow-utils-newxidmap/pubkey.gpg
        repo_gpgcheck: no
        skip_if_unavailable: yes
        enabled: yes

    - name: RedHat | install prerequisites
      become: true
      yum:
        name:
          - shadow-utils46-newxidmap
          - slirp4netns
        state: present

  when: ansible_os_family == 'RedHat'
    and ansible_distribution_version is version('7.6', '<=')

- name: Install packages
  package:
    name: "{{ podman_packages }}"
    state: present

# ==============================================================================
#   Configuration
# ==============================================================================

- name: Podman | Configure
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  loop:
    - etc/containers/libpod.conf
    - etc/containers/registries.conf
    - etc/containers/storage.conf
